//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.08 at 07:13:02 PM PDT 
//


package parsers.pubmed;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the parsers.pubmed package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: parsers.pubmed
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link parsers.pubmed.MedlineCitationSet }
     *
     */
    public MedlineCitationSet createMedlineCitationSet() {
        return new MedlineCitationSet();
    }

    /**
     * Create an instance of {@link parsers.pubmed.PubMedPubDate }
     *
     */
    public PubMedPubDate createPubMedPubDate() {
        return new PubMedPubDate();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Year }
     *
     */
    public Year createYear() {
        return new Year();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Month }
     *
     */
    public Month createMonth() {
        return new Month();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Day }
     *
     */
    public Day createDay() {
        return new Day();
    }

    /**
     * Create an instance of {@link LastName }
     *
     */
    public LastName createLastName() {
        return new LastName();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Chemical }
     *
     */
    public Chemical createChemical() {
        return new Chemical();
    }

    /**
     * Create an instance of {@link parsers.pubmed.PersonalNameSubjectList }
     *
     */
    public PersonalNameSubjectList createPersonalNameSubjectList() {
        return new PersonalNameSubjectList();
    }

    /**
     * Create an instance of {@link parsers.pubmed.PersonalNameSubject }
     *
     */
    public PersonalNameSubject createPersonalNameSubject() {
        return new PersonalNameSubject();
    }

    /**
     * Create an instance of {@link parsers.pubmed.MedlineCitation }
     *
     */
    public MedlineCitation createMedlineCitation() {
        return new MedlineCitation();
    }

    /**
     * Create an instance of {@link parsers.pubmed.PMID }
     *
     */
    public PMID createPMID() {
        return new PMID();
    }

    /**
     * Create an instance of {@link parsers.pubmed.DateCreated }
     *
     */
    public DateCreated createDateCreated() {
        return new DateCreated();
    }

    /**
     * Create an instance of {@link DateCompleted }
     *
     */
    public DateCompleted createDateCompleted() {
        return new DateCompleted();
    }

    /**
     * Create an instance of {@link parsers.pubmed.DateRevised }
     *
     */
    public DateRevised createDateRevised() {
        return new DateRevised();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Article }
     *
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link parsers.pubmed.MedlineJournalInfo }
     *
     */
    public MedlineJournalInfo createMedlineJournalInfo() {
        return new MedlineJournalInfo();
    }

    /**
     * Create an instance of {@link parsers.pubmed.ChemicalList }
     *
     */
    public ChemicalList createChemicalList() {
        return new ChemicalList();
    }

    /**
     * Create an instance of {@link parsers.pubmed.CitationSubset }
     *
     */
    public CitationSubset createCitationSubset() {
        return new CitationSubset();
    }

    /**
     * Create an instance of {@link parsers.pubmed.CommentsCorrectionsList }
     *
     */
    public CommentsCorrectionsList createCommentsCorrectionsList() {
        return new CommentsCorrectionsList();
    }

    /**
     * Create an instance of {@link parsers.pubmed.GeneSymbolList }
     *
     */
    public GeneSymbolList createGeneSymbolList() {
        return new GeneSymbolList();
    }

    /**
     * Create an instance of {@link parsers.pubmed.MeshHeadingList }
     *
     */
    public MeshHeadingList createMeshHeadingList() {
        return new MeshHeadingList();
    }

    /**
     * Create an instance of {@link parsers.pubmed.OtherID }
     *
     */
    public OtherID createOtherID() {
        return new OtherID();
    }

    /**
     * Create an instance of {@link parsers.pubmed.OtherAbstract }
     *
     */
    public OtherAbstract createOtherAbstract() {
        return new OtherAbstract();
    }

    /**
     * Create an instance of {@link parsers.pubmed.KeywordList }
     *
     */
    public KeywordList createKeywordList() {
        return new KeywordList();
    }

    /**
     * Create an instance of {@link parsers.pubmed.SpaceFlightMission }
     *
     */
    public SpaceFlightMission createSpaceFlightMission() {
        return new SpaceFlightMission();
    }

    /**
     * Create an instance of {@link parsers.pubmed.InvestigatorList }
     *
     */
    public InvestigatorList createInvestigatorList() {
        return new InvestigatorList();
    }

    /**
     * Create an instance of {@link parsers.pubmed.GeneralNote }
     *
     */
    public GeneralNote createGeneralNote() {
        return new GeneralNote();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Investigator }
     *
     */
    public Investigator createInvestigator() {
        return new Investigator();
    }

    /**
     * Create an instance of {@link parsers.pubmed.DataBank }
     *
     */
    public DataBank createDataBank() {
        return new DataBank();
    }

    /**
     * Create an instance of {@link parsers.pubmed.AccessionNumberList }
     *
     */
    public AccessionNumberList createAccessionNumberList() {
        return new AccessionNumberList();
    }

    /**
     * Create an instance of {@link parsers.pubmed.ForeName }
     *
     */
    public ForeName createForeName() {
        return new ForeName();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Initials }
     *
     */
    public Initials createInitials() {
        return new Initials();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Suffix }
     *
     */
    public Suffix createSuffix() {
        return new Suffix();
    }

    /**
     * Create an instance of {@link parsers.pubmed.DataBankList }
     *
     */
    public DataBankList createDataBankList() {
        return new DataBankList();
    }

    /**
     * Create an instance of {@link PubDate }
     *
     */
    public PubDate createPubDate() {
        return new PubDate();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Season }
     *
     */
    public Season createSeason() {
        return new Season();
    }

    /**
     * Create an instance of {@link MedlineDate }
     *
     */
    public MedlineDate createMedlineDate() {
        return new MedlineDate();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Pagination }
     *
     */
    public Pagination createPagination() {
        return new Pagination();
    }

    /**
     * Create an instance of {@link parsers.pubmed.StartPage }
     *
     */
    public StartPage createStartPage() {
        return new StartPage();
    }

    /**
     * Create an instance of {@link parsers.pubmed.EndPage }
     *
     */
    public EndPage createEndPage() {
        return new EndPage();
    }

    /**
     * Create an instance of {@link parsers.pubmed.MedlinePgn }
     *
     */
    public MedlinePgn createMedlinePgn() {
        return new MedlinePgn();
    }

    /**
     * Create an instance of {@link ArticleIdList }
     *
     */
    public ArticleIdList createArticleIdList() {
        return new ArticleIdList();
    }

    /**
     * Create an instance of {@link parsers.pubmed.ArticleId }
     *
     */
    public ArticleId createArticleId() {
        return new ArticleId();
    }

    /**
     * Create an instance of {@link AccessionNumber }
     *
     */
    public AccessionNumber createAccessionNumber() {
        return new AccessionNumber();
    }

    /**
     * Create an instance of {@link parsers.pubmed.DeleteCitation }
     *
     */
    public DeleteCitation createDeleteCitation() {
        return new DeleteCitation();
    }

    /**
     * Create an instance of {@link parsers.pubmed.CommentsCorrections }
     *
     */
    public CommentsCorrections createCommentsCorrections() {
        return new CommentsCorrections();
    }

    /**
     * Create an instance of {@link parsers.pubmed.AuthorList }
     *
     */
    public AuthorList createAuthorList() {
        return new AuthorList();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Author }
     *
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link parsers.pubmed.NameID }
     *
     */
    public NameID createNameID() {
        return new NameID();
    }

    /**
     * Create an instance of {@link parsers.pubmed.CollectiveName }
     *
     */
    public CollectiveName createCollectiveName() {
        return new CollectiveName();
    }

    /**
     * Create an instance of {@link parsers.pubmed.PubmedArticle }
     *
     */
    public PubmedArticle createPubmedArticle() {
        return new PubmedArticle();
    }

    /**
     * Create an instance of {@link parsers.pubmed.PubmedData }
     *
     */
    public PubmedData createPubmedData() {
        return new PubmedData();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Grant }
     *
     */
    public Grant createGrant() {
        return new Grant();
    }

    /**
     * Create an instance of {@link parsers.pubmed.URL }
     *
     */
    public URL createURL() {
        return new URL();
    }

    /**
     * Create an instance of {@link parsers.pubmed.History }
     *
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link parsers.pubmed.ObjectList }
     *
     */
    public ObjectList createObjectList() {
        return new ObjectList();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Object }
     *
     */
    public Object createObject() {
        return new Object();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Param }
     *
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link MeshHeading }
     *
     */
    public MeshHeading createMeshHeading() {
        return new MeshHeading();
    }

    /**
     * Create an instance of {@link parsers.pubmed.DescriptorName }
     *
     */
    public DescriptorName createDescriptorName() {
        return new DescriptorName();
    }

    /**
     * Create an instance of {@link parsers.pubmed.QualifierName }
     *
     */
    public QualifierName createQualifierName() {
        return new QualifierName();
    }

    /**
     * Create an instance of {@link parsers.pubmed.Journal }
     *
     */
    public Journal createJournal() {
        return new Journal();
    }

    /**
     * Create an instance of {@link parsers.pubmed.ELocationID }
     *
     */
    public ELocationID createELocationID() {
        return new ELocationID();
    }

    /**
     * Create an instance of {@link Abstract }
     *
     */
    public Abstract createAbstract() {
        return new Abstract();
    }

    /**
     * Create an instance of {@link Language }
     *
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link parsers.pubmed.GrantList }
     *
     */
    public GrantList createGrantList() {
        return new GrantList();
    }

    /**
     * Create an instance of {@link parsers.pubmed.PublicationTypeList }
     *
     */
    public PublicationTypeList createPublicationTypeList() {
        return new PublicationTypeList();
    }

    /**
     * Create an instance of {@link parsers.pubmed.ArticleDate }
     *
     */
    public ArticleDate createArticleDate() {
        return new ArticleDate();
    }

    /**
     * Create an instance of {@link Keyword }
     *
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link ISSN }
     *
     */
    public ISSN createISSN() {
        return new ISSN();
    }

    /**
     * Create an instance of {@link parsers.pubmed.JournalIssue }
     *
     */
    public JournalIssue createJournalIssue() {
        return new JournalIssue();
    }

    /**
     * Create an instance of {@link parsers.pubmed.GeneSymbol }
     *
     */
    public GeneSymbol createGeneSymbol() {
        return new GeneSymbol();
    }

    /**
     * Create an instance of {@link PublicationType }
     *
     */
    public PublicationType createPublicationType() {
        return new PublicationType();
    }

    /**
     * Create an instance of {@link parsers.pubmed.PubmedArticleSet }
     * 
     */
    public PubmedArticleSet createPubmedArticleSet() {
        return new PubmedArticleSet();
    }

}
